# Generated by Django 4.0.3 on 2022-07-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(null=True, upload_to='Blog_images/', verbose_name='Blog Photo')),
                ('blog_content', models.TextField(verbose_name='Blog Content')),
                ('blog_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Blog Date')),
                ('cat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Z', to='serviceApp.category', verbose_name='Blog Category')),
            ],
        ),
    ]
