# Generated by Django 4.0.3 on 2022-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0010_blog_blog_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.TextField(null=True, verbose_name='Blog Title'),
        ),
    ]
