# Generated by Django 4.0.3 on 2022-09-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0012_blog_blog_vid_content_blog_blog_vid_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
